console.log("Model: e premium maxed")
console.log("Model: e premium++")
console.log("Model: e premium+")
console.log("Model: e premium")
console.log("Model: e air nano +")
console.log("Model: e air nano")
console.log("Model: e air++")
console.log("Model: e air")
console.log("Model: e++")
console.log("Model: e+")
console.log("Model: e")
console.log("The one above is the oldest model")