
console.log("Model: e iron")
console.log("Model: e aluminum III")
console.log("Model: e aluminum II")
console.log("Model: e aluminum I")
console.log("Model: e aluminum+++")
console.log("Model: e aluminum++")
console.log("Model: e aluminum+")
console.log("Model: e aluminum")
console.log("Model: e copper III")
console.log("Model: e copper II")
console.log("Model: e copper I")
console.log("Model: e copper++")
console.log("Model: e copper+")
console.log("Model: e copper")
console.log("Model: e premium maxed")
console.log("Model: e premium++")
console.log("Model: e premium+")
console.log("Model: e premium")
console.log("Model: e air nano +")
console.log("Model: e air nano")
console.log("Model: e air++")
console.log("Model: e air")
console.log("Model: e++")
console.log("Model: e+")
console.log("Model: e")
console.log("The one above is the oldest model")